/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

/**
 *
 * @author rangga
 */

import java.io.Reader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.LinkedHashMap;
import java.util.Map;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

//import org.json.JSONObject;

public final class CustomerForm extends javax.swing.JFrame {

    // deklarasi
    Connection con;
    Statement stat;
    PreparedStatement pst = null;
    ResultSet rs;
    String sql;
    String url;
    
    // set as Login
    int u_uid = UserSession.getU_uid(); 
    int u_akses = UserSession.getU_akses();
    String u_nama = UserSession.getU_nama(); 
    String u_email = UserSession.getU_email();
    String u_username = UserSession.getU_username(); 
    String u_hp = UserSession.getU_hp();
    
    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() throws IOException {
        initComponents();
        
        //pemanggilan fungsi koneksi database yang sudah kita buat pada class koneksi.java
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        pst = DB.pst;
        UserLogin();
        tampil_combo();
        cart_table();
        sub_total();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxBrg = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAddCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTmp = new javax.swing.JTable();
        lblFoto = new javax.swing.JLabel();
        txt_id_brg = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        btnClearCart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtZipostal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jCmbProvince = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSubdistrict = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        ComboBoxBrg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxBrgItemStateChanged(evt);
            }
        });
        ComboBoxBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBrgActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI");

        jLabel2.setText("BARANG");

        jLabel3.setText("HARGA");

        txtHarga.setEditable(false);

        jLabel4.setText("QTY");

        btnAddCart.setText("Add Cart");
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });

        jTableTmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID BARANG", "NAMA BARANG", "HARGA", "QTY", "TOTAL"
            }
        ));
        jTableTmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTmp);

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshop/No_Image_Available.jpg"))); // NOI18N

        txt_id_brg.setEditable(false);
        txt_id_brg.setUI(null);
        txt_id_brg.setEnabled(false);

        txtWeight.setText("jTextField1");
        txtWeight.setUI(null);

        btnClearCart.setText("Clear Cart");
        btnClearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCartActionPerformed(evt);
            }
        });

        jLabel5.setText("SUB TOTAL :");

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(27, 8, 8));
        txtSubTotal.setFont(new java.awt.Font("Open Sans", 3, 12)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(42, 228, 74));
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotal.setText("0");
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        jLabel12.setText("NAMA");

        txtNama.setEditable(false);

        txtId.setEditable(false);

        jLabel13.setText("Username");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alamat Tujuan"));

        jLabel10.setText("Kode Pos :");

        txtZipostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipostalActionPerformed(evt);
            }
        });

        jLabel11.setText("Alamat :");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jLabel7.setText("Provinsi :");

        jCmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jawa Barat", "Jawa Tengah", "DKI", "Bali", "Bangka Belitung", "Banten", "Bengkulu", "DI Yogyakarta", "Gorontalo", "Jambi", "Jawa Timur", "Kalimantan Barat", "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Timur" }));

        jLabel8.setText("Kota");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jLabel9.setText("Kecamatan :");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipostal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jCmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtZipostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_id_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 69, Short.MAX_VALUE)
                                                .addComponent(btnAddCart, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                    .addComponent(txtNama))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ComboBoxBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(113, 113, 113)
                                .addComponent(lblFoto))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnClearCart)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearCart)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBrgActionPerformed
        // TODO add your handling code here:
        String SelectItem;
        SelectItem = (String) ComboBoxBrg.getSelectedItem();
        System.out.println(SelectItem);
        if("===Pilih Barang===".equals(SelectItem)){
            // Do Nothing
            System.out.println("====DO Nothing====");
        }else{
            try {
                    sql = "SELECT * FROM product WHERE name =?";
                    pst=con.prepareStatement(sql);
                    pst.setString(1, SelectItem);
                    rs = pst.executeQuery();
                    if(rs.next()){
                        BufferedImage img = null;
                           try {
                                 img = ImageIO.read(getClass().getResource(rs.getString("image")));
                           } catch (IOException e) {
                                        e.printStackTrace();
                           }
                           Image dimg = img.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);
                        txtHarga.setText(rs.getString("price"));
                        txt_id_brg.setText(rs.getString("id"));
                        txtWeight.setText(rs.getString("weight"));
                        // getClass().getResource(rs.getString("image"))
                        ImageIcon image = new ImageIcon(dimg);
                        lblFoto.setIcon(image);
                    }
                } catch(SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_ComboBoxBrgActionPerformed

    private void ComboBoxBrgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxBrgItemStateChanged
      
    }//GEN-LAST:event_ComboBoxBrgItemStateChanged

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
        try {
                sql = "INSERT INTO tmp_cart (id, name, price, qty, weight, user_id) VALUES (?, ?, ?, ?, ?, ?)";
                pst=con.prepareStatement(sql);
                pst.setString(1, txt_id_brg.getText());
                pst.setString(2, (String) ComboBoxBrg.getSelectedItem());
                pst.setString(3, txtHarga.getText());
                pst.setString(4, txtQty.getText());
                pst.setString(5, txtWeight.getText());
                pst.setString(6, txtId.getText());
                boolean cek;
                cek = pst.execute();
                if(cek){
                    JOptionPane.showMessageDialog(null, "gagal menambah barang ke cart");
                }else{
                    
                    cart_table();
                    sub_total();
                    JOptionPane.showMessageDialog(null, "berhasil menambah barang ke cart");
                }
                
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        try {
            sql = "DELETE FROM tmp_cart WHERE user_id=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil Clear barang di cart");
            cart_table();
            sub_total();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtZipostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipostalActionPerformed

    private void jTableTmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTmpMouseClicked

        int selRow = jTableTmp.getSelectedRow();
        int selCol = jTableTmp.getSelectedColumn();
//        if(selCol == 0){
            Object value = jTableTmp.getValueAt(selRow, 0);
            System.out.println(value);
//        }else{
//            JOptionPane.showMessageDialog(null, "Hanya Kolom ID yang bisa diklik");
//        }
    }//GEN-LAST:event_jTableTmpMouseClicked

    // button submit Action
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                    try{
            String sql_total_qty = "SELECT SUM(qty) as total_qty FROM tmp_cart WHERE user_id=?";
            pst=con.prepareStatement(sql_total_qty);
            pst.setString(1, txtId.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                String total_qty;
                String price_total;
                price_total = txtSubTotal.getText();
                total_qty = rs.getString("total_qty");
                System.out.println(price_total);
                System.out.println(total_qty);
                String sql_insert_transaction = "INSERT INTO transaction (user_id, total_qty, price_total) VALUES ("
                        + "?, "
                        + "?, "
                        + "?)";
                pst=con.prepareStatement(sql_insert_transaction);
                pst.setString(1, txtId.getText());
                pst.setString(2, total_qty);
                pst.setString(3, price_total);
                boolean cek = pst.execute();
                if(cek){
                    JOptionPane.showMessageDialog(null, "Gagal Transaksi");
                }else{
                    TransactionDetination();
                    SetNullField();
                    JOptionPane.showMessageDialog(null, "Transaksi Berhasil dibuat!");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new MenuCustomer().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TransactionDetination() throws SQLException
    {
        String province = (String) jCmbProvince.getSelectedItem();            
        String sql_get_trans_id ="SELECT count(id) as transaction_id FROM transaction";
        pst=con.prepareStatement(sql_get_trans_id);
        rs = pst.executeQuery();
        if(rs.next()){
            sql ="INSERT INTO `transaction_destination` (`transaction_id`, `province`, `city`, `subdistrict`, `zip_postal`, `address`) VALUES (?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, rs.getString("transaction_id"));
            pst.setString(2, (String) jCmbProvince.getSelectedItem());
            pst.setString(3, txtCity.getText());
            pst.setString(4, txtSubdistrict.getText());
            pst.setString(5, txtZipostal.getText());
            pst.setString(6, txtAddress.getText());
            pst.execute();
            TransactionDetail(rs.getString("transaction_id"));
        }
                    
    }
    
    private void SetNullField()
    {
        txtCity.setText(null);
        txtSubdistrict.setText(null);
        txtZipostal.setText(null);
        txtAddress.setText(null);
        delete_tmp_cart();
        cart_table();
        sub_total();
    }
    
    private void delete_tmp_cart()
    {
        try{
            sql = "DELETE FROM tmp_cart WHERE user_id =?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            pst.execute();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }
    
    private void TransactionDetail(String tid) throws SQLException
    {
        String get_all_tmp ="SELECT * FROM tmp_cart where user_id=?";
                    pst=con.prepareStatement(get_all_tmp);
                    pst.setString(1, txtId.getText());
                    ResultSet rs_tmp = pst.executeQuery();
                    String transac_id = tid;
                        while(rs_tmp.next()){
                            String item_id = rs_tmp.getString("id");
                            String item_name = rs_tmp.getString("name");
                            String qty = rs_tmp.getString("qty");
                            String item_price = rs_tmp.getString("price");
            int total_price = Integer.parseInt(rs_tmp.getString("qty"))*Integer.parseInt(rs_tmp.getString("price"));
                            String sql_transaction_detail = "INSERT INTO `transaction_detail` (`transaction_id`, `item_id`, `item_name`, `qty`, `item_price`, `total_price`) VALUES (?, ?, ?, ?, ?, ?)";
                            pst=con.prepareStatement(sql_transaction_detail);
                            pst.setString(1, transac_id);
                            pst.setString(2, item_id);
                            pst.setString(3, item_name);
                            pst.setString(4, qty);
                            pst.setString(5, item_price);
                            pst.setString(6, Integer.toString(total_price));
                            pst.execute();
                        }
    }
    
    // get as user login
    
    private void UserLogin()
    {
        txtId.setText(String.valueOf(u_uid));
        txtNama.setText(u_nama);
        txtUsername.setText(u_username);
    }
    
//    private void getJson() throws MalformedURLException, IOException
//    {
//        url = "http://localhost:8006/api/v1/get_province";
//        URL obj = new URL(url);
//        HttpURLConnection conn = (HttpURLConnection) obj.openConnection();
//        // Optional default si GET
//        // add request header
//        conn.setRequestProperty("User-Agent", "Mozilla/5.0");
//        int responseCode = conn.getResponseCode();
//        System.out.println("\nSending GET request URL :"+ url);
//        System.out.println("Response Code :"+ responseCode);
//        BufferedReader in = new BufferedReader(
//                new InputStreamReader(conn.getInputStream())
//        );
//        String InputLine;
//        StringBuffer response = new StringBuffer();
//        while ((InputLine = in.readLine()) != null){
//                response.append(InputLine);
//        }
//        in.close();
//        // print string
//        System.out.println(response.toString());
//        
//        // Read JSON response and print
//        JSONObject myResponse = new  JSONObject(response.toString());
//        System.out.println("result after reading JSON response");
//        System.out.println("Result :"+myResponse);
//        
//    }
    
    private void sub_total()
    {
        try{
            sql = "SELECT sum(price * qty) as subtotal FROM tmp_cart where user_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                String subTotal;
                subTotal = rs.getString("subtotal");
                if(subTotal == null){
                    subTotal = "0";
                }
                txtSubTotal.setText(subTotal);
            }
        } catch (SQLException e){
               JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
    }        
    
    private void cart_table()
    {
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("ID BARANG");
        tb.addColumn("NAMA BARANG");
        tb.addColumn("HARGA");
        tb.addColumn("QTY");
        tb.addColumn("TOTAL");
        jTableTmp.setModel(tb);
        try { 
            sql = "SELECT *, (tmp_cart.price * tmp_cart.qty) as total FROM tmp_cart where user_id=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            rs = pst.executeQuery();
            
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("price"),
                    rs.getString("qty"),
                    rs.getString("total"),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void tampil_combo()
    {
        try {
            sql = "SELECT * FROM product";
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            ComboBoxBrg.addItem("===Pilih Barang===");
            while(rs.next()){
                ComboBoxBrg.addItem(rs.getString("name"));
            }
            
        } catch  (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CustomerForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBrg;
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCmbProvince;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTmp;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtSubdistrict;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipostal;
    private javax.swing.JTextField txt_id_brg;
    // End of variables declaration//GEN-END:variables
}
